Minor updates for CI/CD workflow
First-Peoples-Cultural-Council/fv-be pull request #1045
Opened 2024-09-11 17:43 UTC by sahil97

### Description of Changes
- Added `relative_files` flag to `.coveragerc` for better sonar coverage analysis
- Merged RUN instructions in Dockerfile since sonar was failing the QC on main

### Checklist
- ~README / documentation has been updated if needed~
- ~PR title / commit messages contain Jira ticket number if applicable~
- ~Tests have been updated / created if applicable~
- ~Admin Panel has been updated if models have been added or modified~
- ~Migrations have been updated and committed if applicable~
- ~Insomnia workspace has been updated if applicable~

### Reviewers Should Do The Following:
- [x] Review the code changes here
- ~Pull the branch and test locally~

### Additional Notes
N/A

2024-09-12 18:00 UTC, rohit-fpcc requested changes

2024-09-12 23:03 UTC, rohit-fpcc commented on Dockerfile
> +&& apk add --no-cache libffi-dev \
My bad this looks like is upgraded we need amps now.

2024-09-12 23:09 UTC, rohit-fpcc approved these changes

2024-09-13 00:28 UTC, rohit-fpcc reviewed
Let refactor the docker file as discussed

2024-09-13 15:38 UTC, rohit-fpcc approved these changes

2024-09-13 22:08 UTC, sarahfirstvoices approved these changes

2024-09-13 22:14 UTC, merged