Fw 6275 add validate endpoint for an import job
First-Peoples-Cultural-Council/fv-be pull request #1123
Opened 2024-11-15 22:41 UTC by sahil97

### Description of Changes
- Added `import-jobs/{import-job-id}/validate` endpoint to validate an import-job
- Made importJob optional in `File` model to fix admin interface requiring importJob for media files
- Checks performed before starting a validation job
  - No other job on the same site is queued or running, either for validation or db import
  - The specified job's dry run is not queued or running. 

### Checklist
- [x] README / documentation has been updated if needed
- [x] PR title / commit messages contain Jira ticket number if applicable
- [x] Tests have been updated / created if applicable
- ~Admin Panel has been updated if models have been added or modified~
- ~Migrations have been updated and committed if applicable~
- [x] Insomnia workspace has been updated if applicable

### Reviewers Should Do The Following:
- [x] Review the code changes here
- ~Pull the branch and test locally~

### Additional Notes
N/A

2024-11-20 19:48 UTC, bronson-c submitted a review, later dismissed
LGTM! Just a small nitpick with one of the tests

2024-11-20 19:48 UTC, bronson-c commented on firstvoices/backend/tests/test_apis/test_import_job_api.py
> +    def test_exception_fetching_previous_report(self, caplog):
[minor] I believe you should also assert that the self.import_job.validation_status = JobStatus.FAILED in this test

2024-11-20 23:33 UTC, bronson-c submitted a review, later dismissed
LGTM!

2024-11-21 20:15 UTC, sarahfirstvoices requested changes
Let's chat about the async aspects a bit and make sure all the paths will work

2024-11-21 20:15 UTC, sarahfirstvoices commented on firstvoices/backend/tasks/import_job_tasks.py
> +    old_report = import_job_instance.validation_report
What if there is an old report but they don't choose revalidate? Are we intentionally leaving the old report?

2024-11-21 20:15 UTC, sarahfirstvoices commented on firstvoices/backend/views/import_job_views.py
> +        import_job_id = self.kwargs["pk"]
If there is already a validation in progress from the initial creation, what happens? Should we return a 400 error at this point? We don't have a way to cancel the first validation, and there is no guarantee the two reports will complete in the right order. I think we need to think through the collision cases a bit more

2025-01-07 21:38 UTC, sahil97 commented on firstvoices/backend/views/import_job_views.py
> +        import_job_id = self.kwargs["pk"]
With the changes I just added, if the `/validate` endpoint is hit while a job is queued or running (same job or a different job), it will give a 400 and state that the user should wait for the current job to finish.

2025-01-07 23:34 UTC, sarahfirstvoices commented on firstvoices/backend/tasks/import_job_tasks.py
> +    # If dry-run has not been executed successfully, do not proceed for the db import
Unrelated to these changes, but I just noticed the error log on line 297. Error logs are meant for situations where the code is not running as expected and we need an admin to go fix something asap. This is just a user error being handled appropriately-- I think it should be an info log instead, to avoid noisy alerts for us

2025-01-07 23:36 UTC, sarahfirstvoices commented on firstvoices/backend/tasks/import_job_tasks.py
> +    # If dry-run has not been executed successfully, do not proceed for the db import
That log message actually looks like it is intended for the user and not for the logs-- should we put it into the message on the job instead? Or possibly move this check into the API so we could return a 400 status in this case?

2025-01-07 23:39 UTC, sarahfirstvoices commented on firstvoices/backend/views/import_job_views.py
> +            logger.error(
If this message is meant for the user, it needs to go in the Response object instead of into the logs.

2025-01-07 23:41 UTC, sarahfirstvoices commented on firstvoices/backend/views/import_job_views.py
> +                "The specified job is already running or queued. "
Same issue here-- user messages need to go in the Response object. The easiest way is usually to raise a ValidationError rather than manually constructing the response. Something like `raise raise ValidationError("The specified job is already running etc etc...")`

2025-01-07 23:42 UTC, sarahfirstvoices requested changes
I added a few more comments about logging and error responses, but the async fixes look good to me!

2025-01-15 19:44 UTC, sarahfirstvoices approved these changes

2025-01-15 19:49 UTC, merged