FW-6251 Add draftjs conversion script and HTML cleaning to relevant text fields
First-Peoples-Cultural-Council/fv-be pull request #1142
Opened 2024-12-06 22:08 UTC by bronson-c

### Description of Changes
Please briefly explain the changes here.

### Checklist
- [ ] README / documentation has been updated if needed
- [ ] PR title / commit messages contain Jira ticket number if applicable
- [ ] Tests have been updated / created if applicable
- [ ] Admin Panel has been updated if models have been added or modified
- [ ] Migrations have been updated and committed if applicable
- [ ] Insomnia workspace has been updated if applicable

### Reviewers Should Do The Following:
- [ ] Review the code changes here
- [ ] Pull the branch and test locally

### Additional Notes
N/A

2024-12-09 23:57 UTC, sarahfirstvoices requested changes

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/management/commands/convert_draftjs_to_html.py
> +        logger = logging.getLogger("convert_draftjs_to_html")
To make our logs more predictable, please use `logging.getLogger(__name__)` and just leave it at the default level

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/management/commands/convert_draftjs_to_html.py
> +                logger.info("No sites with the provided slug(s) found.")
I think this one could be a warning

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/management/commands/convert_draftjs_to_html.py
> +            logger.info(f"Converting draftjs content to html for site {site.slug}...")
Looking at this and the rest of the logs in this method-- I think they should all be debug level logs

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/models/base.py
> +class HTMLSanitizedTextField(models.TextField):
Proposed rename: SanitizedHtmlField

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/tests/test_models/test_song_model.py
> +    def test_html_cleaning_fields(self):
These tests don't need to go on the models-- all the logic is in the field, so please just add one test file with tests for the field.

2024-12-09 23:57 UTC, sarahfirstvoices commented on firstvoices/backend/tests/test_models/test_song_model.py
> +    def test_html_cleaning_fields(self):
When you do that, can you please add a test case where we save a non-html string that has some html-related characters in it? I am thinking about the widget settings using the HTML fi1eld for every value. So e.g., the text could be "Why is 1 < 2 ?" or "The French person said << quoi ?? >>"

2024-12-10 18:31 UTC, gmcauliffe commented on firstvoices/backend/management/commands/convert_draftjs_to_html.py
> +                widget__in=site_widgets, key="textWithFormtting"
Spotted a typo: "textWithForm**a**tting"

2024-12-10 18:42 UTC, bronson-c commented on firstvoices/backend/management/commands/convert_draftjs_to_html.py
> +                widget__in=site_widgets, key="textWithFormtting"
fixed! Nice catch

2024-12-20 17:30 UTC, sarahfirstvoices approved these changes

2024-12-20 20:05 UTC, merged