Fw 5069 Refactored hydration utility and added more tests for search related utilities and views
First-Peoples-Cultural-Council/fv-be pull request #659
Opened 2023-11-06 23:57 UTC by sahil97

### Description of Changes
1. Refactored hydration method to use minimal serializers for all responses, thus not requiring request be passed down.
2. Added PersonMinimalSerializer
3. Added tests for 
  - hydration of all objects, i.e. dictionary_entries, songs, stories, images, audio and video
  - testing out errors during hydration process
  - error cases in base search view
4. Excluded search/tasks folder, added that info to a separate ticket to cover that when doing either integration testing or some other way to test celery-elasticsearch interaction.
5. Coverage should be up to ~85% now.

### Checklist
- ~README / documentation has been updated if needed~
- [x] PR title / commit messages contain Jira ticket number if applicable
- [x] Tests have been updated / created if applicable
- ~Admin Panel has been updated if models have been added or modified~
- ~Migrations have been updated and committed if applicable~
- ~Team Postman workspace has been updated if applicable~

### Reviewers Should Do The Following:
- [x] Review the code changes here
- ~Pull the branch and test locally~

### Additional Notes
N/A

2023-11-08 19:05 UTC, sarahfirstvoices requested changes
Mostly looking great! Just that one issue about the startsWithChar test

2023-11-08 19:05 UTC, sarahfirstvoices commented on firstvoices/backend/tests/test_apis/test_search_api.py
> +        assert "startsWithChar=x" in response.request["QUERY_STRING"]
I don't think this is testing anything useful for us (just that you used the correct url on line 311). A better assertion would be something like 

`mock_search_query_execute.assert_called_with(my_expected_value)`

2023-11-08 23:32 UTC, bronson-c approved these changes
LGTM outside of the one test that Sarah has requested changes on, great stuff 👍

2023-11-09 00:19 UTC, sarahfirstvoices commented on firstvoices/backend/tests/test_apis/test_search_api.py
> +        assert mock_get_search_query.call_args.kwargs["starts_with_char"] == "x"
I love this!

2023-11-09 00:19 UTC, sarahfirstvoices approved these changes

2023-11-09 19:46 UTC, merged