FW-5138 Add order by search parameter
First-Peoples-Cultural-Council/fv-be pull request #662
Opened 2023-11-08 23:26 UTC by NolanVH

### Description of Changes
This PR adds the ability to order the search results by the following:
- `dateCreated`: orders results by the created timestamp
- `dateModified`: orders results by the last modified timestamp
- `alphabet`: orders results by the custom order based on the alphabet

A `reverse` boolean parameter has been added that works with the `orderBy` parameter and will reverse the order of results if one of the three parameters above is specified. If the `orderBy` parameter is not used then the `reverse` parameter has no effect.

The created and last_modified values have been added to the search index to support these parameters. Additionally, the `created` and `last_modified` values have been added to the serializers used by the search view.

### Checklist
- ~README / documentation has been updated if needed~
- [x] PR title / commit messages contain Jira ticket number if applicable
- [x] Tests have been updated / created if applicable
- ~Admin Panel has been updated if models have been added or modified~
- ~Migrations have been updated and committed if applicable~
- [ ] Team Postman workspace has been updated if applicable

### Reviewers Should Do The Following:
- [x] Review the code changes here
- [ ] Pull the branch and test locally

### Additional Notes
N/A

2023-11-09 00:28 UTC, sarahfirstvoices requested changes

2023-11-14 18:20 UTC, bronson-c approved these changes
LGTM! 👍

2023-11-15 18:30 UTC, sarahfirstvoices commented on firstvoices/backend/search/utils/query_builder_utils.py
> +        return None, descending
This is fine, but I don't think we really need to return the descending value here

2023-11-15 18:33 UTC, sarahfirstvoices commented on firstvoices/backend/search/utils/query_builder_utils.py
> +        return None, descending
I take it back about this being fine-- I think we should return None, None here to eliminate the possibility of a bug that would sort by reverse search score

2023-11-15 18:34 UTC, sarahfirstvoices commented on firstvoices/backend/views/search/base_search_views.py
> +            if search_params["descending"] and search_params["sort"] is not None
If you always return None for descending when the sort param is missing or invalid, you can skip this type of check on the sort param value

2023-11-15 18:35 UTC, sarahfirstvoices approved these changes
Thanks for making all these changes! I'm approving it, but please do update that one return value

2023-11-16 01:16 UTC, merged