add basic gallery read API
First-Peoples-Cultural-Council/fv-be pull request #739
Opened 2023-12-19 20:08 UTC by bronson-c

### Description of Changes
Please briefly explain the changes here.

### Checklist
- [ ] README / documentation has been updated if needed
- [ ] PR title / commit messages contain Jira ticket number if applicable
- [ ] Tests have been updated / created if applicable
- [ ] Admin Panel has been updated if models have been added or modified
- [ ] Migrations have been updated and committed if applicable
- [ ] Team Postman workspace has been updated if applicable

### Reviewers Should Do The Following:
- [ ] Review the code changes here
- [ ] Pull the branch and test locally

### Additional Notes
N/A

2023-12-19 23:23 UTC, NolanVH requested changes
Aside from the minor prefetching comment, these changes are looking great! Tested locally and all APIs are working as intended.

I am wondering if the gallery cover images are supposed to be unique across galleries or are multiple galleries supposed to be allowed to have the same cover image? Right now the cover image is a one-to-one field with a gallery and we may want to modify it to allow different galleries to use the same cover image.

2023-12-19 23:23 UTC, NolanVH commented on firstvoices/backend/views/gallery_views.py
> +            .select_related("cover_image")
Some additional prefetching of the image and thumbnail fields could be added here to ensure low response times. Feel free to send me a message if you want to connect on this.

2024-01-04 18:05 UTC, sahil97 approved these changes
Agree with Nolan's comment related to adding support for multiple galleries to use common image for cover.
except for that LGTM !

2024-01-08 17:50 UTC, NolanVH approved these changes
LGTM!

2024-01-08 19:01 UTC, merged